name: Smoke Tests - PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        run: echo












# clonar meu projeto
# instalar o java
# instalar o chrome
# instalar o chrome driver
# executar o testes
# gerar o relatorio
